name: ❔ Needing Help
description: You have regular questions? Then ask them here...
title: "[Help] "
labels: ["help"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please **dont share** personal contact data (for sample `E-Mail` or `Discord`-Name), we never contact you here because we dont offer premium-support.
  - type: textarea
    id: what-happened
    attributes:
      label: Question
      description: Tell us what you need help with!
      placeholder: Your question
    validations:
      required: true
